## The two functions makeCacheMatrix and cacheSolve can be used to solve for the inverse of a given matrix. 
## They also store the result in order to save computing time in the future.

## The makeCacheMatrix takes an invertible matrix as input and generates a list of 
## four functions ('set','get','setinverse','getinverse') which allow you to interact
## with the input matrix and its inverse (stored or freshly generated)

makeCacheMatrix <- function(x = matrix()) {
    m <- NULL
    set <- function(y) {
        x <<- y
        m <<- NULL
    }
    get <- function() x
    setinverse <- function(solve) m <<- solve
    getinverse <- function() m
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## The cacheSolve function uses the list of functions generated by makeCacheMatrix to
## either retrieve the inverse of a previously solved matrix or solves for the inverse 
## of the input matrix and stores the result.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    m <- x$getinverse()
    if(!is.null(m)){
        message("getting cached data")
        return(m)
    }
    data <- x$get()
    m <- solve(data, ...)
    x$setinverse(m)
    m
}
